# The general config file for TheoryViz

# Geometry colors
background_color = "black"
vertex_color = "white"
vertex_text_color = "black"
vertex_stroke_color = "white"
edge_color = "white"
text_color = "white"
table_border_color = "white"

# Theory Colors
current_state_color = "yellow"
final_state_color = "white"
initial_state_color = "white"
transition_color = "yellow"

# Geometry Config
vertex_radius = 2
layout_scale = 2
layout_type = "kamada_kawai"

# Theory Config
show_initial_state_arrow = true
show_final_state_annulus = true
