# The general config file for TheoryViz

background_color = "black"
vertex_color = "white"
vertex_text_color = "black"
edge_color = "white"
text_color = "white"
table_border_color = "white"

current_state_color = "yellow"
final_state_color = "white"
initial_state_color = "white"
transition_color = "yellow"

vertex_radius = 0.08
layout_scale = 2
layout_type = "kamada_kawai"

show_initial_state_arrow = true
show_final_state_annulus = true
