[scene]
background_color = "black"

[graph]
layout_scale = 2
layout = "circular"

[graph.vertex]
radius = 0.3
color = "white"
stroke_color = "white"

[graph.vertex.label]
color = "black"
font_size = 30

[graph.edge]
color = "white"

[graph.edge.label]
label_position = 0.4  # Some float between 0 and 1, how far along the line is the label?
font_size = 30

[graph.edge.label.label]
color = "white"
fill_color = "white"

[graph.edge.label.frame]
color = "white"

[graph.edge.label.box]
color = "black"

[theory] 
show_initial_state_arrow = true
show_final_state_annulus = true
initial_state_color = "white"
final_state_color = "white"
current_state_color = "yellow"
transition_color = "yellow"

[text]
color = "white"
shadow_color = "gray"
font_size = 30

[table]
border_color = "white"
scale = 0.7

[program]
debug_mode = true

# [ledger]
# #scene                   Sets background color       
# max_steps = 3
# speed = 1.0
# size = 1.0
# fade_speed = 1.0
# spacing = 1.2
# arrow_color = "white"

# [ledger.past]
# font_size = 30
# text_color = "black"
# circle_color = "blue"
#
# [ledger.symbol]
# font_size = 30
# text_color = "black"
# box_color = "yellow"
#
# [ledger.next]
# font_size = 30
# text_color = "black"
# circle_color = "purple"
