[scene]
background_color = "black"

[graph]
layout_scale = 2
layout = "circular"

[graph.vertex]
radius = 0.3
color = "white"
stroke_color = "white"

[graph.vertex.label]
color = "black"
font_size = 30

[graph.edge]
color = "white"

[graph.edge.label]
label_position = 0.4  # Some float between 0 and 1, how far along the line is the label?
font_size = 30

[graph.edge.label.label]
color = "white"
fill_color = "white"

[graph.edge.label.frame]
color = "white"

[graph.edge.label.box]
color = "black"

[theory]
show_initial_state_arrow = true
show_final_state_annulus = true
initial_state_color = "white"
final_state_color = "white"
current_state_color = "yellow"
transition_color = "yellow"

[text]
color = "white"
shadow_color = "gray"
font_size = 30

[table]
border_color = "white"
scale = 0.7

[program]
debug_mode = true
