# The lightmode config file for TheoryViz

# Geometry colors
background_color = 0xeeeee4
vertex_color = "black"
vertex_text_color = 0xeeeee4
vertex_stroke_color = "black"
edge_color = "black"
edge_text_color = "black"
table_border_color = "black"

# Theory Colors
current_state_color = 0xe28743
final_state_color = "black"
initial_state_color = "black"
transition_color = 0xe28743

# Geometry Config
vertex_radius = 0.4
layout_scale = 2
layout_type = "kamada_kawai"
font_size = 40
edge_label_position = 0.5 # Must be [0,1], how far along the line is label?
edge_label_frame = true # Should edge label have a frame?
edge_label_frame_fill = 0xeeeee4
edge_label_frame_opacity = 1 # [0,1]

# Theory Config
show_initial_state_arrow = true
show_final_state_annulus = true
