# Geometry colors
background_color = 0x000000  # Black
vertex_color = 0xFFD700  # Gold
vertex_text_color = 0x000000  # White
vertex_stroke_color = 0xFFD700  # Gold
edge_color = 0xFF4500  # OrangeRed
edge_text_color = 0xFFFFFF  # White
table_border_color = 0xFF4500  # OrangeRed

# Theory Colors
current_state_color = 0x00FF00  # Lime
final_state_color = 0xFFD700  # Gold
initial_state_color = 0xFFD700  # Gold
transition_color = 0x00FF00  # Lime

# Geometry Config
vertex_radius = 0.3
layout_scale = 2
layout_type = "kamada_kawai"
font_size = 40
edge_label_position = 0.5 
edge_label_frame = true 
edge_label_frame_fill = 0x000000  # Black
edge_label_frame_opacity = 1 

# Theory Config
show_initial_state_arrow = true
show_final_state_annulus = true

