# Geometry colors
background_color = 0xF5F5DC  # Beige
vertex_color = 0x8B4513  # Saddle Brown
vertex_text_color = 0xFFFFFF  # White
vertex_stroke_color = 0x8B4513
edge_color = 0xA0522D  # Sienna
edge_text_color = 0xA0522D
table_border_color = 0xA0522D

# Theory Colors
current_state_color = 0xFFD700  # Gold
final_state_color = 0xFFFFFF  # White
initial_state_color = 0xFFFFFF  # White
transition_color = 0xFFD700  # Gold

# Geometry Config
vertex_radius = 0.3
layout_scale = 2
layout_type = "kamada_kawai"
font_size = 40
edge_label_position = 0.5 
edge_label_frame = true 
edge_label_frame_fill = 0xF5F5DC
edge_label_frame_opacity = 1 

# Theory Config
show_initial_state_arrow = true
show_final_state_annulus = true

