# Geometry colors
background_color = 0x1E1E1E
vertex_color = 0xC8C8C8
vertex_text_color = 0x1E1E1E
vertex_stroke_color = 0xC8C8C8
edge_color = 0xC8C8C8
edge_text_color = 0xC8C8C8
table_border_color = 0xC8C8C8

# Theory Colors
current_state_color = 0xFFA500  # Orange
final_state_color = 0xC8C8C8
initial_state_color = 0xC8C8C8
transition_color = 0xFFA500  # Orange

# Geometry Config
vertex_radius = 0.4
layout_scale = 2
layout_type = "kamada_kawai"
font_size = 40
edge_label_position = 0.5 
edge_label_frame = true 
edge_label_frame_fill = 0x1E1E1E
edge_label_frame_opacity = 0.8 

# Theory Config
show_initial_state_arrow = true
show_final_state_annulus = true

