# Geometry colors
background_color = 0xE0FFFF  # Light Cyan
vertex_color = 0x4682B4  # Steel Blue
vertex_text_color = 0xFFFFFF  # White
vertex_stroke_color = 0x4682B4
edge_color = 0x5F9EA0  # Cadet Blue
edge_text_color = 0x5F9EA0
table_border_color = 0x5F9EA0

# Theory Colors
current_state_color = 0x20B2AA  # Light Sea Green
final_state_color = 0xFFFFFF  # White
initial_state_color = 0xFFFFFF  # White
transition_color = 0x20B2AA  # Light Sea Green

# Geometry Config
vertex_radius = 0.3
layout_scale = 2
layout_type = "kamada_kawai"
font_size = 40
edge_label_position = 0.5 
edge_label_frame = true 
edge_label_frame_fill = 0xE0FFFF
edge_label_frame_opacity = 1 

# Theory Config
show_initial_state_arrow = true
show_final_state_annulus = true

